version: '2'

services:

  web: 
    image: node:6.1
    volumes: 
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm install -g nodemon ; nodemon -e js,jade app.js'
    ports: 
      - "80:3000"
    depends_on:
      - mongo
    environment: 
      MONGODB_URI: "mongodb://mongo:27017/hackathon"

  mongo:
    image: mongo:3
    command: mongod --smallfiles